name: Deploy Next.js to CloudBase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Install CloudBase CLI
        run: npm install -g @cloudbase/cli

      - name: Deploy to Tencent CloudBase
        env:
          TCB_SECRET_ID: ${{ secrets.SECRETID }}
          TCB_SECRET_KEY: ${{ secrets.SECRETKEY }}
        run: |
          tcb login --apiKeyId $TCB_SECRET_ID --apiKey $TCB_SECRET_KEY --use-local
          tcb framework deploy --force
